### ISSUE TITLE
Disallow multiple attempts

### ISSUE THREAD

**Issue by cashewpillar** [xtian18/kweeznuts#11]
Possible ba sa frontend side na after makafinish ng 1 attempt ilock na yung quiz for the student? for integrity and stuff lang sa data gathering

cc @ralf-t @xtian18 @XSeed21 @jebjebs

**Comment by arem-t-gh** [comment]
I think possible thru if else. Sounds good to me para less kalat

**Comment by xtian18** [comment]
i think possible. pwede ko icheck sa mga nireturn na quiz kung existing na yung code na inenter

**Comment by xtian18** [comment]
tinry ko kaso may problema pala, nirereturn din pala ng get quizzes kahit d pa submitted. so pag nagstop sa quiz, narerecognize sya as taken na kaya d na makakabalik ulit

**Comment by cashewpillar** [comment]
yung attempt object meron siyang `is_done` attribute na magiging true lang kapag nagsend ng get request sa `/finish` endpoint (quiz submitted)

**Comment by xtian18** [comment]
ok na nadeploy ko na changes, tho d pa nagrereflect sakin ewan ko lang sa side nyo

**Comment by cashewpillar** [comment]
working na saken thankss
