### ISSUE TITLE
Deploy This App

### ISSUE THREAD

**Issue by cashewpillar** [xtian18/kweeznuts#3]
**Frontend To-Dos:**
- [x] Deploy to any platform: [Vercel](https://vercel.com/docs)/ GCP/ AWS/ MS Azure, [see doc for resources](https://github.com/ripienaar/free-for-dev#major-cloud-providers)
    - Use https://inquizitor-test.herokuapp.com/docs or your localhost for the backend
- [x] Raise any performance issues or concerns on [this page](https://github.com/Iionsroar/inquizitor/issues/34)

**Comment by xtian18** [comment]
@Iionsroar @ralf-t  nagtry kami magdeploy sa heroku ang eto lumabas na error... backend problem ba to dahil sa cors?
![image](https://user-images.githubusercontent.com/58137485/185749873-e3ceff7b-7d1b-485d-b81b-eb91f0de7361.png)

**Comment by cashewpillar** [comment]
mukhang sa backend nga, currently testing fix

**Comment by arem-t-gh** [comment]
will send the proper configs sa backend

**Comment by cashewpillar** [comment]
new pull @ main, for testing 

https://inquizitor-test.herokuapp.com/

**Comment by cashewpillar** [comment]
new pull @ main
fix link: https://github.com/Iionsroar/inquizitor/issues/43

**Comment by cashewpillar** [comment]
tagging @xtian18 @XSeed21
